{{- if .Values.istio.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.istio.virtualService.name }}
spec:
  hosts:
  - {{ .Values.istio.virtualService.hosts | first }}
  http:
  {{- toYaml .Values.istio.virtualService.http | nindent 4 }}
{{- end }}
