# service-b-v1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
      version: v1
  template:
    metadata:
      labels:
        app: service-b
        version: v1
    spec:
      containers:
      - name: service-b
        image: ubuntu:22.04
        command: ["/bin/sh", "-c"]
        args:
          - |
            apt-get update && \
            apt-get install -y curl python3 && \
            echo "
            from http.server import BaseHTTPRequestHandler, HTTPServer

            class Handler(BaseHTTPRequestHandler):
                def do_GET(self):
                    self.send_response(200)
                    self.end_headers()
                    self.wfile.write(b'Hello from Service B v1')

            HTTPServer(('', 80), Handler).serve_forever()
            " > /server.py && \
            python3 /server.py
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: service-b
