istio:
  virtualService:
    enabled: true
    name: service-b
    hosts:
      - service-b
    http:
      - route:
          - destination:
              host: service-b
              subset: v1
            weight: 99
          - destination:
              host: service-b
              subset: v2
            weight: 1
  destinationRule:
    enabled: true
    name: service-b
    host: service-b
    subsets:
      - name: v1
        labels:
          version: v1
      - name: v2
        labels:
          version: v2
