title: Traffic Istio Workshop
remote_theme: zendesk/jekyll-theme-zendesk-garden@main

sidebar:
  - overview
  - label: Exercises
    children:
      - exercise1
      - exercise2
      - exercise3
      - exercise4
  - cleanup
